sudo: false

language: node_js

node_js:
  - '8'
  - '9'
  - '10'
  - '11'
  - '12'
  - '13'

jobs:
  allow_failures:
    - node_js: 11
    - node_js: 12
    - node_js: 13

after_script:
  - npm run coveralls

after_failure:
  - tar -cjf "svg-sprite_travis_${TRAVIS_BUILD_NUMBER}.tar.bz2" tmp && curl --ftp-create-dirs -T "svg-sprite_travis_${TRAVIS_BUILD_NUMBER}.tar.bz2" -u $FTP_USER:$FTP_PASSWORD "ftp://jkphl.is/${TRAVIS_REPO_SLUG}/svg-sprite_travis_${TRAVIS_BUILD_NUMBER}.tar.bz2"

matrix:
  fast_finish: true
